const baseURL = 'https://api.clashofclans.com/v1'
const token = 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiIsImtpZCI6IjI4YTMxOGY3LTAwMDAtYTFlYi03ZmExLTJjNzQzM2M2Y2NhNSJ9.eyJpc3MiOiJzdXBlcmNlbGwiLCJhdWQiOiJzdXBlcmNlbGw6Z2FtZWFwaSIsImp0aSI6IjM5MjVmYzhkLTQ1MTctNDdjOS1iM2JmLWFmYTQ5MGMyZTNlYyIsImlhdCI6MTYzMzU5MDQwOCwic3ViIjoiZGV2ZWxvcGVyLzQwMDQ2ODczLWZjOTYtM2FmYy0wZDRjLWNkNDRkZDE2ODQ5OSIsInNjb3BlcyI6WyJjbGFzaCJdLCJsaW1pdHMiOlt7InRpZXIiOiJkZXZlbG9wZXIvc2lsdmVyIiwidHlwZSI6InRocm90dGxpbmcifSx7ImNpZHJzIjpbIjIyMy4xNjYuMTA0LjE1MSJdLCJ0eXBlIjoiY2xpZW50In1dfQ.iqsvDIDtL2Toiudwpei7UwsOBrq9TgsTvrJ0VM2-nTli-kQbRJ3TlRrAp6UinoGRa7dlMCk5l6HzslmWZeWEPQ'

module.exports = {
  baseURL, token
}
